from skills import BaseSkill
from tasks.registry import pick_task_ai
from ai.providers import get_ai_provider
from datetime import datetime


class NewsBriefingSkill(BaseSkill):
    name = "news_briefing"
    description = "生成统一格式的 Markdown 新闻简报"
    description_ja = "統一されたMarkdown形式のニュースブリーフィングを生成"
    description_en = "Generate unified Markdown news briefings"
    keywords = ["新闻简报", "每日新闻", "今日头条", "news briefing", "daily news", "news summary"]

    # 统一的 Markdown 模板
    MARKDOWN_TEMPLATE = """
# 🗞️ {{subject}} | {{date}}

---

### 🌟 今日头条 | Top Stories
{{top_stories}}

---

### 🔍 深度洞察 | Deep Dive
{{deep_dive}}

---

### 💡 行业快讯 | Quick Hits
{{quick_hits}}

---
*Generated by MailMindHub | AI Powered Email Assistant*
"""

    def run(self, payload: dict, ai_caller=None) -> str:
        query = payload.get("query") or payload.get("prompt") or "最新 AI 与科技动态"
        lang = payload.get("lang") or "zh"
        subject = payload.get("subject") or "新闻简报"
        
        ai_name, backend = pick_task_ai(payload)
        ai = get_ai_provider(ai_name, backend)
        
        # 构建指令，强制 AI 使用统一的 Markdown 格式
        now_str = datetime.now().strftime("%Y-%m-%d")
        
        prompt = f"""
请针对以下主题生成一份新闻简报："{query}"
当前日期：{now_str}
要求使用以下 Markdown 格式输出（直接返回填充后的内容，不要包含 JSON 以外的文字）：

# 🗞️ {subject} | {now_str}

---

### 🌟 今日头条 | Top Stories
- **[新闻标题]** (来源: [媒体名])
  - [简洁摘要，2-3句话总结核心内容]
  - [阅读更多] (URL链接，如果有)
- [重复以上结构 2-3 次]

---

### 🔍 深度洞察 | Deep Dive
[对当前主题的 1-2 段深度分析或趋势总结]

---

### 💡 行业快讯 | Quick Hits
- [简短的新闻快讯 1]
- [简短的新闻快讯 2]
- [简短的新闻快讯 3]

---
*Generated by MailMindHub | AI Powered Email Assistant*

注意：
1. 优先使用你的联网搜索能力获取最新真实信息。
2. 如果无法获取实时信息，请基于已知知识库生成。
3. 请确保链接（如有）的准确性。
4. 必须严格遵循上述 Markdown 结构。
5. 语言请使用：{lang}。
"""
        
        # 如果 AI 支持原生搜索，给予更高权重
        if backend.get("native_web_search"):
            prompt = "请使用你的联网搜索能力完成以下请求：\n" + prompt

        result = ai.call(prompt)
        return result or "⚠️ 简报生成失败，AI 无响应。"


SKILL = NewsBriefingSkill()
